### ISSUE TITLE
UDI8 and UDI9 not working

### ISSUE THREAD

**Issue by APINYK** [Nykredit/openshift_test#4]
registry.redhat.io/devspaces/udi-rhel8
registry.redhat.io/devspaces/udi-rhel9 

not working i devfile.

**Comment by APINYK** [comment]
@vitaliy-guliy do you know why these arent working anymore?

**Comment by vitaliy-guliy** [comment]
I think it make sense to switch to quay.io instead.
I've created a corresponding PR
https://github.com/Nykredit/openshift_test/pull/5

**Comment by vitaliy-guliy** [comment]
@APINYK do you have registry.redhat.io working again?

**Comment by APINYK** [comment]
@vitaliy-guliy Yes it works again. Thanks! What is the difference between quai.io and registry.redhat.io - Both seem to be hosted by redhat?
