### ISSUE TITLE
Restart devspace not working after upgrading to Red Hat Enterprise Linux release 9.3

### ISSUE THREAD

**Issue by APINYK** [Nykredit/openshift_test#7]
Devspace env: 
![image](https://github.com/Nykredit/openshift-test/assets/127222595/72bf1c22-e7b0-4565-9116-27c4c2a1abdb)

Both "restart" and "restart "from local dev file" seems to be dead: 
![image](https://github.com/Nykredit/openshift-test/assets/127222595/77336424-8afb-4d1c-84d6-eb2cc062ca99)

Error message:
![image](https://github.com/Nykredit/openshift-test/assets/127222595/8f125e80-c76f-44c6-9aee-36bd0a10a8c5)

**Comment by APINYK** [comment]
@vitaliy-guliy after we upgraded to the latest version of openshift dev spaces we can't restart our workspaces.

**Comment by vitaliy-guliy** [comment]
@APINYK I will take a look

**Comment by APINYK** [comment]
Thanks! 👍
