### ISSUE TITLE
Newest version of extension is not available in DevSpaces (Tested in the official sandbox).

### ISSUE THREAD

**Issue by APINYK** [Nykredit/openshift_test#8]
DevSpaces VSCode (I have tested in the official sandbox and our own environment) for the sonarlint extension: 
![image](https://github.com/Nykredit/openshift-test/assets/127222595/a74dcbd5-042c-4656-b01d-0ee400e595a2)

CodeSpaces and desktop VSCode: 
![image](https://github.com/Nykredit/openshift-test/assets/127222595/a371cec1-2f3e-4dab-a03c-73aa94ddd87a)

How is this possible? We need the latest version to be able to fix another issue regarding the sonarlint extension.

**Comment by APINYK** [comment]
@vitaliy-guliy do you know about this problem?

**Comment by vitaliy-guliy** [comment]
@APINYK 

VS Code desktop uses marketplace with SonarLint 4.3.0
https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode

DevSpaces uses Open VSX Registry with SonarLint 4.2.2
https://open-vsx.org/extension/SonarSource/sonarlint-vscode

A new version is not published yet to Open VSX Registry, the job publishing the extension failed for some reasons
https://github.com/SonarSource/sonarlint-vscode/actions/runs/7723423704

But if you want to use it, you can download the extension binary somewhere in the workspace and then install the extension from the file.

![Screenshot from 2024-02-14 11-51-43](https://github.com/Nykredit/openshift-test/assets/1655894/0c8ff727-e574-4ac9-8b82-09922681a35b)

**Comment by vitaliy-guliy** [comment]
There is a pull request to fix that https://github.com/SonarSource/sonarlint-vscode/pull/529

**Comment by APINYK** [comment]
@vitaliy-guliy great! Thanks for clarrifying!

**Comment by APINYK** [comment]
@vitaliy-guliy is it possible to change to VS Code desktop marketplace? Would be nice to have the two alligned.

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy is it possible to change to VS Code desktop marketplace? Would be nice to have the two alligned.

I cannot say exactly, but there `OPENVSX_REGISTRY_URL="https://open-vsx.org"` environment variable to change the URI to the marketplace.

The variable is checked here
https://github.com/che-incubator/che-code/blob/main/launcher/src/openvsix-registry.ts
and used to update `product.json`
https://github.com/che-incubator/che-code/blob/main/code/product.json#L105-L108

So it needs to find a valid URI to vscode marketplace.

**Comment by vitaliy-guliy** [comment]
btw, a new version of sonarlint is published to Open VSX registry

**Comment by APINYK** [comment]
@vitaliy-guliy 

Ok thanks! [Yes, I told](https://community.sonarsource.com/t/conneted-mode-token-dissappears-after-vscode-restart/109085) them to fix it, after they asked me to upgrade to the newest version, when I asked them about the secure storage issue with sonarlint. Unfortunately and as expected the newest version didn't resolve the issue as the issue is not related to sonarlint - as you know its an Dev Spaces/Eclipse Che issue. Do you have anything new on this topic - did you create an issue or similar that I can follow?

**Comment by vitaliy-guliy** [comment]
I think sonarlint only uses the plugin API and sonarlint team ideally should do not care where the token is saved.
It is VS Code responsibility. I'm going to create a simple extension to test the case today. Will post the result here https://github.com/Nykredit/openshift-test/issues/10 
If it is a bug, it could affect other extensions.

**Comment by APINYK** [comment]
Thanks! I look very much forward to hearing about the result!

**Comment by vitaliy-guliy** [comment]
@APINYK take a look here https://github.com/Nykredit/openshift-test/issues/10
